### ISSUE TITLE
[Feature Request] Product SKU 

### ISSUE THREAD

**Issue by asrafulattare** [AppCheap/roadmap#105]
Hi, @dangtienngoc 
Could you please add the product details page to show **SKU** & also search work via **SKU**

**Comment by dangtienngoc** [comment]
That feature support in Cirilla 3.0.0

![image](https://user-images.githubusercontent.com/4260689/177507075-1a63e5bd-8364-46b1-9ada-7fb9bdc1a217.png)


https://codecanyon.net/item/cirilla-multipurpose-flutter-wordpress-app/31940668

Please download latest on Codecanyon and try

Thank you.

**Comment by asrafulattare** [comment]
and Sku search?
