### ISSUE TITLE
unable to change image, button size on custom product detail page

### ISSUE THREAD

**Issue by yasararafat009** [AppCheap/roadmap#106]
when i changed size, width , its contiously loading. 
When i saved and opened the app - its show blank
![ciri1](https://user-images.githubusercontent.com/65075219/175938823-98fca2ba-9b02-4cb5-b553-690e637f609d.png)

**Comment by dangtienngoc** [comment]
hi there,

The issue please submit here: https://admin.appcheap.io/ticket
