### ISSUE TITLE
Razorpay not working in custom flow

### ISSUE THREAD

**Issue by yasararafat009** [AppCheap/roadmap#107]
in webview mode - razorpay working fine
In custom flow mode - razorpay payment popup not apperar 
I attached 
![ciri2](https://user-images.githubusercontent.com/65075219/175939497-19885e8f-0f4b-400a-878b-ac96b4b27f28.png)
custom flow razorpay payment
![ciri3](https://user-images.githubusercontent.com/65075219/175939683-8654df4c-a139-4e0c-ac4c-5558dd0c056c.png)
In this there is a wording - pay through razorpay. but its not showing (show blank in bubble)
In COC - its showing
![ciri4](https://user-images.githubusercontent.com/65075219/175940218-f1661c07-498f-4bed-a1b9-c1d3737ad039.png)
After click payment - its show blank

**Comment by dangtienngoc** [comment]
hi there,

The issue please submit here: https://admin.appcheap.io/ticket
