### ISSUE TITLE
Issue After activating push notification plugin

### ISSUE THREAD

**Issue by yasararafat009** [AppCheap/roadmap#108]
Whenever i login to my website - [Error i got a issue A Critical error on this website]

using php 8.1
debug file - 
PHP Deprecated:  strstr(): Passing null to parameter #1 ($haystack) of type string is deprecated in /home/XXXX/public_html/wp-content/plugins/woocommerce/includes/wc-page-functions.php on line 139

wc-page-functions.php on line 139 This code 
if ( strstr( $path, $customer_logout ) || strstr( $query, $customer_logout ) ) {
					unset( $items[ $key ] );

**Comment by yasararafat009** [comment]
I also changed php version like 7.4, 8.0 - still have same error

**Comment by dangtienngoc** [comment]
I will look in to, but in the error above not show from push notification plugin
