### ISSUE TITLE
[Issue] After update App builder plugin 2.9.0

### ISSUE THREAD

**Issue by yasararafat009** [AppCheap/roadmap#110]
After update App builder plugin 2.9.0 - wordpress crash [error like  a critical error occured]
its working fine in 7.4
But 8.0,8.1 its not working
Please check bro
push plugin also crash in all php version

**Comment by dangtienngoc** [comment]
hi,

You can enable debug mode to see the error

https://wordpress.org/support/article/debugging-in-wordpress/
