### ISSUE TITLE
BookingWp Add Ons not work in app.

### ISSUE THREAD

**Issue by bakpaorabbit** [AppCheap/roadmap#112]
you miss something here. @dangtienngoc 
as I told you that BookingWp is including Woocommerce Product Add Ons. So when you have Individual WooCommerce Products Add Ons plugin, it will deactivated automatically because BookingWp built in WooCommerce Products Add On.

The problem is, when you use BookingWP. all simple product with Add Ons will not show in app.

I make it simple. So when we :

1. Install woocommerce product add ons = you cannot use bookingwp

2. Install bookingwp = you cannot use product add on even though the plugin already includes the same plugin : woocommerce product add ons. If you use, then all simple product with add ons will not show in the app

Need solution to use BookingWP but with featured Add Ons.

**Comment by dangtienngoc** [comment]
The issue could you submit to admin.appcheap.io/tickes

Thank you.
