### ISSUE TITLE
Remove or Hidden email field on register screen

### ISSUE THREAD

**Issue by quangbahoa** [AppCheap/roadmap#117]
Hi there,

In some case that customers are not have email address sow We need to remove/hidden email field.

Thanks

**Comment by findhimrl** [comment]
like it.
app user registation from doesn't verify emil /Mobile otp.
#So allow us to diseable/hide Registation form.

**Comment by dangtienngoc** [comment]
This feature supported on Cirilla v3.1.0

**Comment by findhimrl** [comment]
i khow that. but i want you to give us power to hide full registation form.
or edit that.
