### ISSUE TITLE
Otp issue

### ISSUE THREAD

**Issue by almodroid** [AppCheap/roadmap#126]
I have an issue with sms Otp it shows error after entering the correct code only in the login screen  

in the register screen it logins without Otp if I enter only the phone number it login direct 

![F5615155-4C7F-4C9C-9AB7-526AFF1F8E67](https://user-images.githubusercontent.com/45069954/179103490-e563504b-f0b7-4379-a34e-01d2759e1a97.png)

**Comment by dangtienngoc** [comment]
Could you create the issue here: https://admin.appcheap.io/tickets
