### ISSUE TITLE
problem  plugin Bookingwp

### ISSUE THREAD

**Issue by sasamanny** [AppCheap/roadmap#137]
When scheduling reservations, for example, from 2:00 pm to 10:00 pm
In the application, when choosing the date and the same day or another day, an error appears "sorry the selected slot is not available " https://b.top4top.io/p_2395xkoph1.jpeg
And when specifying the days of the week only, without specific dates
In the application, you can choose any day except the same day, an error appears "you must choose a future date and time."https://d.top4top.io/p_2395ckh6e1.jpeg

**Comment by bakpaorabbit** [comment]
question for you : add on works on your side ? on my side, the product not show in app when I enable add on in appointment product. please check and let me know.

**Comment by dangtienngoc** [comment]
In the latest we fixed that issue

Also here for feature request we close the issue here
