### ISSUE TITLE
Loading bar not showing in webview page loading (Android)

### ISSUE THREAD

**Issue by rifatspir** [AppCheap/roadmap#14]
Loading bar not working properly in Android. Its fine in iOS. 
For example, if someone click from cart page to **process checkout** it don't showing the loading bar properly. As a result it shows blank white screen until the page load fully. Same issue in WebView widget.

**Comment by rifatspir** [comment]
This one is very important please focus on it.  @dangtienngoc

**Comment by dangtienngoc** [comment]
@rifatspir It related flutter core the issue reproduction here: https://github.com/flutter/flutter/issues/96186

I'm waiting for a fix from the Flutter core team.
