### ISSUE TITLE
ACF field Not showing 17aug update

### ISSUE THREAD

**Issue by findhimrl** [AppCheap/roadmap#162]
ACF field Not showing 17 August Update.

![wwwwwwwwwwwwwwwwww](https://user-images.githubusercontent.com/75209116/186765767-87b98bed-632b-4733-a06b-84911712eb47.PNG)

**Comment by dangtienngoc** [comment]
I'm response in your ticket

Thank you

**Comment by findhimrl** [comment]
tikcket response slow and left.waiting since 2days, for ans. problem Not solve.
