### ISSUE TITLE
Support: Native payment Stripe, Paypal, Razorpay

### ISSUE THREAD

**Issue by dangtienngoc** [AppCheap/roadmap#2]
- [x] Create UI

Request:

- [x]  Stripe: https://codecanyon.net/author_dashboard?filter=unread&term=Native+payment#comment_27140015

- [x] Razorpay pay: https://codecanyon.net/author_dashboard?filter=unread&term=Native+payment#comment_26886729

- [x] Paypal

**Comment by dangtienngoc** [comment]
@crazyhosts Yes, I have add to list

**Comment by crazyhosts** [comment]
Dear Appcheap

pls add  auto detect OTP Login or add Mobile No. Sign Up 
fix Signup issue

**Comment by dangtienngoc** [comment]
hi,

What do you mean detect OTP?

**Comment by crazyhosts** [comment]
> hi,
> 
> What do you mean detect OTP?

Yes

**Comment by Dada70** [comment]
Do you have any idea when razorpay native payment gateway update comes???

**Comment by msurchy** [comment]
Will be a great feature to add Klarna Checkout

**Comment by DrXripper** [comment]
Eagerly waiting for this update, also had a couple of questions as of now we flow redirects us to checkout where customers can select the address add a personal note, and checkout, are we solving all of these issues on this update with native payment gateways?

**Comment by hadrongh** [comment]
I'm patiently waiting for this update...please add Paystack payment gateway. They're a subsidiary of Stripe and it's mainly used in Africa. Thank you

**Comment by lorus123** [comment]
I suggest you to roll out the update with the tasks already done and keep working on this issue and update again when done.

**Comment by UAE50** [comment]
Hello, when will the update be released, I want to buy the app

**Comment by UAE50** [comment]
@dangtienngoc any update sir

**Comment by dangtienngoc** [comment]
@UAE50 We release the latest v2.6.0 on Codecanyon.

**Comment by DrXripper** [comment]
> @UAE50 We release the latest v2.6.0 on Codecanyon.

When?

**Comment by crazyhosts** [comment]
how to enable native checkout

**Comment by dangtienngoc** [comment]
@crazyhosts Could you join our support,

We have problem here when register sanbox account with Paytm

Could you join our support system, I need you help for support Paytm

**Comment by crazyhosts** [comment]
@dangtienngoc  yes tell me

**Comment by crazyhosts** [comment]
@dangtienngoc if you need Paytm account i can provide you

**Comment by dangtienngoc** [comment]
@crazyhosts Yes,

Could you sent to my email: ngocdt@rnlab.io

**Comment by crazyhosts** [comment]
@dangtienngoc  Could you check your email just send the access of business.paytm.com

**Comment by crazyhosts** [comment]
@dangtienngoc 
 https://business.paytm.com/integration-builder/account-setup
 https://prnt.sc/qd2OCjNGN1Z-    Test API Details

**Comment by dangtienngoc** [comment]
@crazyhosts Thank you I have logged in

**Comment by hadrongh** [comment]
@dangtienngoc Please do well to add paystack https://paystack.com

**Comment by dangtienngoc** [comment]
@hadrongh The Paystack well done, we have only Issue with Paytm when it support access only Indian

**Comment by hadrongh** [comment]
@dangtienngoc Thanks for supporting paystack
