### ISSUE TITLE
Admob feature

### ISSUE THREAD

**Issue by Hadharm** [AppCheap/roadmap#34]
Please add interstitial and rewarded admob ads to display after "X seconds" on any screen we want. 

X seconds should be be editable for us to choose.

Pls add this in next update.

e.g. I want to place interstitial ads inside the app. I want it after 5 secs on some screens (post favourite screen, posts screen, all pages screen and profile screen. Also rewarded in profile screen and shop category screen. Also cirilla ads bottom to show on blog list, post category, post favourite and all pages screen.

**Futures**

- [x] Show interstitial display after "X seconds"  on any screen
- [x] [Subscribe to hide ads](https://github.com/AppCheap/roadmap/issues/91)
- [x] Play video to close ADS

**Comment by Hadharm** [comment]
sorry I meant interstitial and rewarded AdMob

**Comment by ramoooi** [comment]
@dangtienngoc
