### ISSUE TITLE
Exclude  "X" posts From Posts blocks

### ISSUE THREAD

**Issue by lorus123** [AppCheap/roadmap#43]
When i add two Latest post block in a screen , it show same posts. But i want to show 1 to 5 posts in first block and 6 to 10 posts in second block. Add a option to exclude "X" posts

**Comment by dangtienngoc** [comment]
Instead, exclude 1->5 first posts.

I will add config one config page in the widget "Post latest"

with 2 option **page** and **per_page** You can config as you wish

Ex:

Widget 1: page = 1, per_page = 5 It will always load 5 first posts
Widget 2: page = 2, per_page = 5 It will load 6 => 10

**Comment by lorus123** [comment]
So basically widget 2 is excluding the posts mentioned in Previous widget that is 5.

**Comment by lorus123** [comment]
If i place one widget where i want to show 6 to 10 posts.

Any possibility to achieve with this?

**Comment by dangtienngoc** [comment]
> So basically widget 2 is excluding the posts mentioned in the Previous widget that is 5.

No need to exclude, the just widget you query posts start from page 2

| page 1| page 2|
|1,2,3,4,5| 6,7,8,9|

**Comment by lorus123** [comment]
okay , add this.

we will check and improve it later (if required).
