### ISSUE TITLE
Language support error!!

### ISSUE THREAD

**Issue by jayhong416** [AppCheap/roadmap#58]
Hi team, I've tried to use the app builder plugin in Korean. But the error occurs every time.

Please add Korean for the next update! We can't do anything because of this.

![image](https://user-images.githubusercontent.com/58717338/158076236-3669c1e3-d7b9-401e-846c-bcf5de0d7351.png)

**Comment by jayhong416** [comment]
![image](https://user-images.githubusercontent.com/58717338/158076279-8e38da86-ff2e-440c-b0f6-521d87a941da.png)

When I click app mode, the screen freezes. I've added title in Korean, didn't change anything except this.

**Comment by dangtienngoc** [comment]
@jayhong416 Did you bought the source code on https://codecanyon.net/item/cirilla-multipurpose-flutter-wordpress-app/31940668

After buying leave for me the ticket here: https://admin.appcheap.io/ticket I will be there and help you resolve the problem.

**Comment by jayhong416** [comment]
@dangtienngoc Got it, I'll send a ticket :)

**Comment by jayhong416** [comment]
@dangtienngoc Got it, I'll send a ticket :)
