### ISSUE TITLE
Default profile image

### ISSUE THREAD

**Issue by jayhong416** [AppCheap/roadmap#60]
Hi team, This app uses the default Gravatar image and users cannot change it.

Please let us change the default profile image & Let users can change it on the app.

Thanks

**Comment by dangtienngoc** [comment]
Default WordPress does not allow users to change the avatar,  only change on Gravatar. 

Do you use the plugin to use change the avatar on the web?

**Comment by dangtienngoc** [comment]
@jayhong416 In the version 2.9.0 we support get default Avatar config from WP admin, also avatar local plugin.
