### ISSUE TITLE
Table, Admob and Video Issues

### ISSUE THREAD

**Issue by Hadharm** [AppCheap/roadmap#67]
Good day, pls i want to add cirilla bottom banner ads (the banner that floats at the bottom) on profile screen, blog post list screen, post category screen, and post favourite screen.

Pls what screens will I edit and what code should be included.

Also, I noticed youtube videos and HTML table tags don't load in the latest release version. Pls, can you confirm from your end to be sure I am not the only one facing this issue?

**Comment by lorus123** [comment]
@dangtienngoc  #64

**Comment by Hadharm** [comment]
After showing fellow developers the table tag issues. They claimed the issue of table tags and video not displaying is from the app builder plugin and not the source code. Pls @dangtienngoc kindly look out and correct this.
