### ISSUE TITLE
Meta (Facebook) Audience network ads

### ISSUE THREAD

**Issue by lorus123** [AppCheap/roadmap#7]
Please support Audience network ads at same places where currently support admob.

Allow user to choose which ad to show admob or audience network for every single ad.

eg.

[ads network="AB" ...]  AB =Admob      
[ads network="AN" ...] AN=Audience Network

https://www.facebook.com/audiencenetwork/monetize

**Comment by dangtienngoc** [comment]
@lorus123 Do you mean support both Firebase and Facebook?

**Comment by lorus123** [comment]
@dangtienngoc 
Support Facebook ads not facebook analytics.

facebook ads are like google admob.

**Comment by lorus123** [comment]
@dangtienngoc  https://pub.dev/packages/facebook_audience_network

**Comment by dangtienngoc** [comment]
@lorus123 I know But in the source code necessary use both Admob and Audience Network.

Or only one enough?

**Comment by lorus123** [comment]
Both.

You can create 3 versions if you wish.

Admob , facebook , both.

Thank you.

**Comment by lorus123** [comment]
You can setup facebook ads via admob mediation.They are moved to bidding only.

https://www.facebook.com/audiencenetwork/move-to-bidding
