### ISSUE TITLE
Menu problem

### ISSUE THREAD

**Issue by lorus123** [AppCheap/roadmap#87]
The 3 dot menu has some problems.

1) When i open a custom link from sidebar and after opening that screen , if i click on menu **instead of opening  , it go back to home**.

2)Menu does not open when swipe from left to right. (open only in home screen)

**Comment by dangtienngoc** [comment]
hi there,

I close ticket because this for repo for features request. If you facing any issues please submit to admin.appcheap.io/ticket.

Thank you.
