### ISSUE TITLE
Still waiting for Update

### ISSUE THREAD

**Issue by Hadharm** [AppCheap/roadmap#88]
Pls it is over one half months and we haven't see any new update concerning most of the critical errors to be fixed inside the app.

**Comment by lorus123** [comment]
@Hadharm  I think the developers no longer operate this app.

**Comment by Hadharm** [comment]
Then I should ask for refund. I just bought the app and have not even launch my app.

**Comment by lorus123** [comment]
@Hadharm Same here , i also have not launch my app yet. Because the app lack some basic features , if i launch the app without that features the app will fail. All the marketing will go waste.

**Comment by crazyhosts** [comment]
waiting for Update

**Comment by ramoooi** [comment]
same here

**Comment by dangtienngoc** [comment]
I close the ticket, it does not relate to any features.
