### ISSUE TITLE
Update on Woocommerce booking system?

### ISSUE THREAD

**Issue by davidom0101** [AppCheap/roadmap#89]
This has been requested many times in the codecanyon comment section, and you have said its something that you are working on?

bookingwp has an API and best functionality.
https://bookingwp.com/

InsireUI have already implemented this in their app:
https://codecanyon.net/item/fluxstore-woocommerce-flutter-ecommerce-full-app/24050041

**Comment by bakpaorabbit** [comment]
+1 for this @dangtienngoc

**Comment by dangtienngoc** [comment]
I close the feature request it create here: https://github.com/AppCheap/roadmap/issues/72

We working on it and support next update
