### ISSUE TITLE
Remove ads option

### ISSUE THREAD

**Issue by lorus123** [AppCheap/roadmap#91]
Please add a option to remove ads for users.

Users will able to disable all ads by paying a specific amount.After successful payment all ads in app will be disabled.

Eg pay 1$ /month to remove ads  Or  Pay 10$/Year .

**Comment by dangtienngoc** [comment]
But we do not support the feature subscribe on the app, we will get back this when the app supports free/pro feature.

**Comment by dangtienngoc** [comment]
I move it to here for east tracking https://github.com/AppCheap/roadmap/issues/34

**Comment by dangtienngoc** [comment]
@lorus123 please check this
https://appcheap.io/docs/cirilla-developers-docs/admob/hide-ads/
